<?php
// Event log, PHP error handler and encrypted audit log.

function event_log_write($case_id, $event_level, $description, $audit_log_file = "-") {
    // Logging function.
    if (!isset($_SESSION['user']['token'])) {
        $sessiontoken = "-";
    } else {
        $sessiontoken = $_SESSION['user']['token'];
    }

    if (!isset($_SESSION['user']['username'])) {
        $session_username = "-";
    } else {
        $session_username = $_SESSION['user']['username'];
    }

    $case_id = filter_numbers($case_id);
    $description = str_replace(array("\r", "\n"), ' ', $description); // Keep one event per line.
    $log = date('d/M/Y:H:i:s O').';'.$session_username.';'.$event_level.';"'.$description.'";'.$_SERVER['REQUEST_URI'].';'.$_SERVER['REMOTE_ADDR'].';'.$audit_log_file.';Session ID: '.$sessiontoken.';';

    if ($case_id === "0") {
        file_put_contents('logs/kirjuri.log', $log."-;\r\n", FILE_APPEND);
        return true;
    }
    else {
        if (!file_exists('logs/cases/')) {
            mkdir('logs/cases');
        }
        if (!file_exists('logs/cases/uid'. $case_id)) {
            mkdir('logs/cases/uid'. $case_id);
        }
        $case_logfile = 'logs/cases/uid' . $case_id . '/events.log';
    }
    file_put_contents($case_logfile, $log."\r\n", FILE_APPEND);
    file_put_contents('logs/kirjuri.log', $log."uid".$case_id.";"."\r\n", FILE_APPEND);
    return true;
}


function kirjuri_error_handler($errno, $errstr, $errfile, $errline) // Trigger an error
{
    global $prefs;
    if (!(error_reporting() & $errno)) {
        return false; // Error suppressed with @ or excluded by error_reporting.
    }
    if (isset($prefs['settings']['show_errors']) && $prefs['settings']['show_errors'] === '1') {
        // Show a message if errors are permitted on screen.
        $errnums = array(
            '1' => 'Error',
            '2' => 'Warning',
            '4' => 'Parse error',
            '8' => 'Notice',
            '16' => 'Core error',
            '32' => 'Compile warning',
            '64' => 'Compile error',
            '128' => 'Compile warning',
            '256' => 'User error',
            '512' => 'User warning',
            '1024' => 'User notice',
            '2048' => 'Strict',
            '4096' => 'Recoverable error',
            '8192' => 'Deprecated',
            '16384' => 'User deprecated',
            '32767' => 'All errors'
        );
        $_SESSION['message']['type'] = 'error';
        $_SESSION['message']['content'] = (isset($errnums[$errno]) ? $errnums[$errno] : 'Error').': '.$errstr;
        $_SESSION['message_set'] = true;
    }
    event_log_write('0', 'Error', $errno.' '.$errstr.', File: '.$errfile.', line '.$errline);
}


function audit_log_write($post_data) {
    // Store an audit log entry of the request.
    if (!file_exists('conf/audit_credentials.php')) {
        // Autogenerate an audit log encryption key on first entry.
        file_put_contents('conf/audit_credentials.php', '<?php return "'.generate_token(64).'" ?>', LOCK_EX);
        event_log_write('0', 'Audit', 'No encryption key found at conf/audit_credentials.php, audit log encryption key autogenerated.');
    }
    if (isset($post_data['REVERT_FROM_AUDIT'])) {
        event_log_write('0', 'Update', "Pushed audit log entry back to database: " . $post_data['REVERT_FROM_AUDIT']);
    }
    $data['user']['username'] = $_SESSION['user']['username'];
    $data['user']['ip_address'] = $_SERVER['REMOTE_ADDR'];
    $data['user']['user_agent'] = isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
    $data['user']['referer'] = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
    $data['user']['request_uri'] = $_SERVER['REQUEST_URI'];
    $data['user']['request_method'] = $_SERVER['REQUEST_METHOD'];
    $data['request_contents'] = $post_data;
    $data = json_encode($data, JSON_PRETTY_PRINT);
    $audit_file_sha256 = hash('sha256', $data);
    $data = encrypt($data, include 'conf/audit_credentials.php');
    $audit_file_epoch = time();

    if (!file_exists('logs/audit/' . substr($audit_file_epoch, 0, 6))) {
        mkdir('logs/audit/' . substr($audit_file_epoch, 0, 6));
    }
    $auditfile_identifier = $audit_file_epoch . "_". strtoupper(generate_token(4)) . ".log";
    if (file_put_contents('logs/audit/' . substr($audit_file_epoch, 0, 6) . '/' . $auditfile_identifier, $data)) {
        event_log_write('0', 'Audit', 'Logged request '. $auditfile_identifier .', sha256: '. $audit_file_sha256);
        return $auditfile_identifier;
    }
    else {
        return "Audit file failure.";
    }
}
